ansible_user: ec2-user
ansible_password: DevOps321
MONGODB_HOST: mongodb-dev.ananthsolutions.online
REDIS_HOST: redis-dev.ananthsolutions.online
CATALOGUE_HOST: catalogue-dev.ananthsolutions.online
MYSQL_HOST: mysql-dev.ananthsolutions.online
CART_HOST: cart-dev.ananthsolutions.online
RABBIT_HOST: rabbitmq-dev.ananthsolutions.online
USER_HOST: user-dev.ananthsolutions.online
SHIPPING_HOST: shipping-dev.ananthsolutions.online
PAYMENT_HOST: payment-dev.ananthsolutions.online