[local]
localhost
[mongodb]
mongodb-dev.ananthsolutions.online

[catalogue]
catalogue-dev.ananthsolutions.online

[redis]
redis-dev.ananthsolutions.online

[user]
user-dev.ananthsolutions.online

[cart]
cart-dev.ananthsolutions.online

[mysql]
mysql-dev.ananthsolutions.online

[shipping]
shipping-dev.ananthsolutions.online

[rabbitmq]
rabbitmq-dev.ananthsolutions.online

[payment]
payment-dev.ananthsolutions.online

[Frontend]
frontend-dev.ananthsolutions.online


