- name: app set up
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yaml
- name: node js setup
  ansible.builtin.import_role:
    name: common 
    tasks_from: nodejs-setup.yaml
- name: systemd setup
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup.yaml

- name: install mongodb
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: present
- name: check if data exisit in mongodb
  ansible.builtin.command:  mongosh --host "{{ MONGODB_HOST }}" --quiet  --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
  register: mongooutput
- name: load data
  ansible.builtin.shell: mongosh --host "{{ MONGODB_HOST }}" </app/db/master-data.js
  when: mongooutput.stdout | int < 0
- name: enable catalogue
  ansible.builtin.systemd:
    name: catalogue
    state: started
    enabled: yes












